### ISSUE TITLE
👨🏾‍💻 Do Exercise 01: Towards a more useful fixed-point number class

### ISSUE THREAD

**Issue by gabrieldejesus** [gabrieldejesus/42-cpp-module-02#4]
### 📋 Tasks

Add the following public constructors and public member functions to my class:

- [x] A constructor that takes a **constant integer** as a parameter.
It converts it to the corresponding fixed-point value. The fractional bits value is
initialized to 8 like in exercise 00.

- [x] A constructor that takes a constant floating-point number as a parameter.
It converts it to the corresponding fixed-point value. The fractional bits value is
initialized to 8 like in exercise 00.

- [x] A member function `float toFloat( void ) const`;
that converts the fixed-point value to a floating-point value.

- [x] A member function `int toInt( void ) const`;
that converts the fixed-point value to an integer value.

And add the following function to the **Fixed** class files:

- [x] An overload of the insertion `(«)` operator that inserts a floating-point representation
of the fixed-point number into the output stream object passed as parameter.

--- 
### 🧪 Testing

```c++
int main( void ) {
  Fixed a;
  Fixed const b( 10 );
  Fixed const c( 42.42f );
  Fixed const d( b );

  a = Fixed( 1234.4321f );

  std::cout << "a is " << a << std::endl;
  std::cout << "b is " << b << std::endl;
  std::cout << "c is " << c << std::endl;
  std::cout << "d is " << d << std::endl;

  std::cout << "a is " << a.toInt() << " as integer" << std::endl;
  std::cout << "b is " << b.toInt() << " as integer" << std::endl;
  std::cout << "c is " << c.toInt() << " as integer" << std::endl;
  std::cout << "d is " << d.toInt() << " as integer" << std::endl;

  return (0);
}
```

### What is a fixed-point number?

A fixed-point number is a type of representation for numerical values, particularly in computer programming, where a specific number of digits `(bits)` are allocated for the fractional part and a specific number for the integer part. It's a compromise between floating-point and integer representations.

In contrast to floating-point numbers, where the decimal point can "float" depending on the magnitude of the number, in fixed-point representation, the position of the decimal point is fixed. This means a fixed-point number has a constant precision, determined by the number of fractional bits allocated.

For example, in a fixed-point representation with 8 fractional bits:

- 1.00000000 (binary) would represent 1.0 in decimal.
- 0.10000000 (binary) would represent 0.5 in decimal.
- 0.01100000 (binary) would represent 0.375 in decimal.

Fixed-point arithmetic can be useful in situations where floating-point arithmetic is too slow, too imprecise, or not supported by the hardware. It's often used in embedded systems, signal processing, and other applications where efficiency and determinism are critical.

So, fixed-point numbers are like rulers where you have a fixed number of marks after the decimal point, and each mark represents a specific fraction of a whole unit. It's a way to represent numbers where precision is fixed and the decimal point doesn't move.
