### ISSUE TITLE
👨🏾‍💻 Do Exercise 02: Now we’re talking

### ISSUE THREAD

**Issue by gabrieldejesus** [gabrieldejesus/42-cpp-module-02#5]
### 📋 Tasks

Add public member functions to your class to overload the following operators:

- [ ] The 6 comparison operators: >, <, >=, <=, == and !=.
- [ ] The 4 arithmetic operators: +, -, *, and /.
- [ ] The 4 increment/decrement (pre-increment and post-increment, pre-decrement and post-decrement) operators, that will increase or decrease the fixed-point value from the smallest representable ϵ such as 1 + ϵ > 1.

Add these four public overloaded member functions to your class:

- [ ] A static member function min that takes as parameters two references on fixed-point numbers, and returns a reference to the smallest one.
- [ ] A static member function min that takes as parameters two references to constant fixed-point numbers, and returns a reference to the smallest one.
- [ ] A static member function max that takes as parameters two references on fixed-point numbers, and returns a reference to the greatest one.
- [ ] A static member function max that takes as parameters two references to constant fixed-point numbers, and returns a reference to the greatest one.
